language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t bluehave/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true bluehave/react-test-app npm run test

after_success:
  - docker build -t bluehave/docker-frontend ./frontend
  - docker build -t bluehave/docker-backend ./backend
  - docker build -t bluehave/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin_open

  - docker push bluehave/docker-frontend
  - docker push bluehave/docker-backend
  - docker push bluehave/docker-nginx
